import { WebClient, Block, KnownBlock } from '@slack/web-api'
import {
  OutputPlugin,
  DeliverRequest,
  DeliverResponse,
  getFinalContent,
  runOutputPlugin,
} from '@narratorlog/sdk'

interface SlackConfig {
  channel: string
  mention?: string
  bot_token_env?: string
  unfurl_links?: boolean
}

class SlackOutputPlugin implements OutputPlugin {
  async deliver(request: DeliverRequest): Promise<DeliverResponse> {
    const config = request.config as unknown as SlackConfig

    const tokenEnv = config.bot_token_env ?? 'SLACK_BOT_TOKEN'
    const token = process.env[tokenEnv]

    if (!token) {
      return {
        success: false,
        error: `${tokenEnv} environment variable not set`,
      }
    }

    const content = getFinalContent(request)
    const client = new WebClient(token)

    try {
      const blocks = buildBlocks(request, content, config)

      const response = await client.chat.postMessage({
        channel: config.channel,
        text: buildFallbackText(request),
        blocks,
        unfurl_links: config.unfurl_links ?? false,
      })

      if (!response.ok) {
        return { success: false, error: `Slack API error: ${response.error}` }
      }

      const ts = response.ts ?? ''
      const channelID = response.channel ?? config.channel

      return {
        success: true,
        reference: `https://slack.com/archives/${channelID}/p${ts.replace('.', '')}`,
        message: `Posted to ${config.channel}`,
      }
    } catch (err) {
      return { success: false, error: String(err) }
    }
  }
}

function buildFallbackText(request: DeliverRequest): string {
  const from = new Date(request.scan.scan_from).toLocaleDateString('en-GB')
  const to = new Date(request.scan.scan_to).toLocaleDateString('en-GB')
  return `${request.scan.repository} changelog — ${from} to ${to}`
}

function buildBlocks(
  request: DeliverRequest,
  content: string,
  config: SlackConfig
): (Block | KnownBlock)[] {
  const from = new Date(request.scan.scan_from).toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric',
  })
  const to = new Date(request.scan.scan_to).toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric',
  })

  const blocks: (Block | KnownBlock)[] = []

  // Header
  blocks.push({
    type: 'header',
    text: {
      type: 'plain_text',
      text: `${request.scan.repository} — ${from} to ${to}`,
    },
  })

  // Mention if configured
  if (config.mention) {
    blocks.push({
      type: 'section',
      text: { type: 'mrkdwn', text: config.mention },
    })
  }

  blocks.push({ type: 'divider' })

  // Split content into Slack-sized chunks (max 3000 chars per block)
  const chunks = splitIntoChunks(content, 2900)
  for (const chunk of chunks) {
    blocks.push({
      type: 'section',
      text: { type: 'mrkdwn', text: chunk },
    })
  }

  blocks.push({ type: 'divider' })

  // Attribution footer
  blocks.push({
    type: 'context',
    elements: [
      {
        type: 'mrkdwn',
        text: 'Generated by <https://narratorlog.dev|narratorlog>',
      },
    ],
  })

  return blocks
}

function splitIntoChunks(text: string, maxLen: number): string[] {
  if (text.length <= maxLen) return [text]

  const chunks: string[] = []
  const lines = text.split('\n')
  let current = ''

  for (const line of lines) {
    if ((current + '\n' + line).length > maxLen) {
      if (current) chunks.push(current.trim())
      current = line
    } else {
      current = current ? current + '\n' + line : line
    }
  }

  if (current.trim()) chunks.push(current.trim())
  return chunks
}

runOutputPlugin(new SlackOutputPlugin())