import OpenAI from 'openai'
import {
  AIProviderPlugin,
  SummarizeRequest,
  SummarizeResponse,
  GenerateRequest,
  GenerateResponse,
  SummarizeGroupInput,
  AudienceInput,
  runAIPlugin,
} from '@narratorlog/sdk'

const CHARS_PER_TOKEN = 4
const MAX_DIFF_CHARS = 3000 * CHARS_PER_TOKEN

class OpenAIPlugin implements AIProviderPlugin {
  async summarize(request: SummarizeRequest): Promise<SummarizeResponse> {
    const client = new OpenAI({
      apiKey: request.api_key,
      baseURL: request.base_url,
    })

    try {
      const response = await client.chat.completions.create({
        model: request.model,
        max_tokens: 300,
        messages: [{ role: 'user', content: buildSummarizePrompt(request.group) }],
      })

      const text = response.choices[0]?.message.content ?? ''
      return {
        summary: text.trim(),
        tokens_used: (response.usage?.prompt_tokens ?? 0) + (response.usage?.completion_tokens ?? 0),
      }
    } catch (err) {
      return { summary: '', error: String(err) }
    }
  }

  async generate(request: GenerateRequest): Promise<GenerateResponse> {
    const client = new OpenAI({
      apiKey: request.api_key,
      baseURL: request.base_url,
    })

    try {
      const response = await client.chat.completions.create({
        model: request.model,
        max_tokens: 2000,
        messages: [{ role: 'user', content: buildGeneratePrompt(request) }],
      })

      const text = response.choices[0]?.message.content ?? ''
      return {
        content: text.trim(),
        tokens_used: (response.usage?.prompt_tokens ?? 0) + (response.usage?.completion_tokens ?? 0),
      }
    } catch (err) {
      return { content: '', error: String(err) }
    }
  }
}

function buildSummarizePrompt(group: SummarizeGroupInput): string {
  const parts: string[] = []

  parts.push(`You are a technical writer creating internal changelog entries.`)
  parts.push(`Summarize the following code change in 2-3 sentences.`)
  parts.push(`Be specific about what changed and why it matters.`)
  parts.push(`Do not use marketing language.`)
  parts.push(``)

  if (group.pr_title) parts.push(`Pull Request: ${group.pr_title}`)
  if (group.pr_description) parts.push(`Description: ${group.pr_description}`)
  if (group.issue_titles.length > 0) parts.push(`Linked Issues: ${group.issue_titles.join(', ')}`)
  if (group.changed_files.length > 0) parts.push(`Changed Files: ${group.changed_files.join(', ')}`)
  if (group.codebase_context) parts.push(`Context:\n${group.codebase_context}`)
  if (group.diff) {
    const diff = group.diff.length > MAX_DIFF_CHARS
      ? group.diff.slice(0, MAX_DIFF_CHARS) + '\n... [truncated]'
      : group.diff
    parts.push(`Diff:\n${diff}`)
  }

  return parts.join('\n')
}

function buildGeneratePrompt(request: GenerateRequest): string {
  const parts: string[] = []

  parts.push(audienceSystemPrompt(request.audience))
  parts.push(``)
  parts.push(`Repository: ${request.repository}`)
  parts.push(`Period: ${formatDate(request.scan_from)} to ${formatDate(request.scan_to)}`)
  parts.push(``)
  parts.push(`What shipped this week:`)
  request.summaries.forEach((s, i) => parts.push(`${i + 1}. ${s}`))
  parts.push(``)
  parts.push(`Write the changelog now. Group by type (Features, Fixes, etc.).`)
  parts.push(`End with: "Generated by narratorlog · narratorlog.dev"`)

  return parts.join('\n')
}

function audienceSystemPrompt(audience: AudienceInput): string {
  const toneMap: Record<string, string> = {
    technical: `You are writing a technical changelog for engineers. Be precise. Mention affected systems or APIs where relevant.`,
    'plain-english': `You are writing a weekly update for an engineering manager. Use plain English. Focus on what was completed.`,
    'benefit-focused': `You are writing product release notes for a product manager. Focus on features from a user perspective. No jargon.`,
    'marketing-friendly': `You are writing public-facing release notes. Highlight new capabilities in customer-friendly language.`,
    friendly: `You are writing customer-facing release notes. Use friendly, clear language. Focus on what's new for the user.`,
  }

  return toneMap[audience.tone]
    ?? `Write a changelog for the ${audience.id} audience with a ${audience.tone} tone.`
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })
}

runAIPlugin(new OpenAIPlugin())