import Anthropic from '@anthropic-ai/sdk'
import {
  AIProviderPlugin,
  SummarizeRequest,
  SummarizeResponse,
  GenerateRequest,
  GenerateResponse,
  SummarizeGroupInput,
  AudienceInput,
  runAIPlugin,
} from '@narratorlog/sdk'

// Rough token estimate — 1 token ≈ 4 chars
const CHARS_PER_TOKEN = 4
const MAX_DIFF_TOKENS = 3000
const MAX_DIFF_CHARS = MAX_DIFF_TOKENS * CHARS_PER_TOKEN

class AnthropicPlugin implements AIProviderPlugin {
  async summarize(request: SummarizeRequest): Promise<SummarizeResponse> {
    const client = new Anthropic({ apiKey: request.api_key })

    try {
      const message = await client.messages.create({
        model: request.model,
        max_tokens: 300,
        messages: [{ role: 'user', content: buildSummarizePrompt(request.group) }],
      })

      const text = message.content.find(b => b.type === 'text')?.text ?? ''
      return {
        summary: text.trim(),
        tokens_used: message.usage.input_tokens + message.usage.output_tokens,
      }
    } catch (err) {
      return { summary: '', error: String(err) }
    }
  }

  async generate(request: GenerateRequest): Promise<GenerateResponse> {
    const client = new Anthropic({ apiKey: request.api_key })

    try {
      const message = await client.messages.create({
        model: request.model,
        max_tokens: 2000,
        messages: [{ role: 'user', content: buildGeneratePrompt(request) }],
      })

      const text = message.content.find(b => b.type === 'text')?.text ?? ''
      return {
        content: text.trim(),
        tokens_used: message.usage.input_tokens + message.usage.output_tokens,
      }
    } catch (err) {
      return { content: '', error: String(err) }
    }
  }
}

function buildSummarizePrompt(group: SummarizeGroupInput): string {
  const parts: string[] = []

  parts.push(`You are a technical writer creating internal changelog entries.`)
  parts.push(`Summarize the following code change in 2-3 sentences.`)
  parts.push(`Be specific about what changed and why it matters.`)
  parts.push(`Do not use marketing language. Do not include implementation details unless they affect behaviour.`)
  parts.push(``)

  if (group.pr_title) {
    parts.push(`Pull Request: ${group.pr_title}`)
  }
  if (group.pr_description) {
    parts.push(`Description: ${group.pr_description}`)
  }
  if (group.issue_titles?.length) {
    parts.push(`Linked Issues: ${group.issue_titles.join(', ')}`)
  }
  if (group.changed_files?.length) {
    parts.push(`Changed Files: ${group.changed_files.join(', ')}`)
  }
  if (group.codebase_context) {
    parts.push(`Codebase Context:\n${group.codebase_context}`)
  }
  if (group.diff) {
    const diff = group.diff.length > MAX_DIFF_CHARS
      ? group.diff.slice(0, MAX_DIFF_CHARS) + '\n... [truncated]'
      : group.diff
    parts.push(`Diff:\n${diff}`)
  }

  return parts.join('\n')
}

function buildGeneratePrompt(request: GenerateRequest): string {
  const parts: string[] = []

  parts.push(audienceSystemPrompt(request.audience))
  parts.push(``)
  parts.push(`Repository: ${request.repository}`)
  parts.push(`Period: ${formatDate(request.scan_from)} to ${formatDate(request.scan_to)}`)
  parts.push(``)
  parts.push(`What shipped this week:`)
  request.summaries.forEach((s, i) => parts.push(`${i + 1}. ${s}`))
  parts.push(``)
  parts.push(`Write the changelog now. Group changes by type (Features, Fixes, Improvements, etc.).`)
  parts.push(`End with this exact line: "Generated by narratorlog · narratorlog.dev"`)

  return parts.join('\n')
}

function audienceSystemPrompt(audience: AudienceInput): string {
  const toneMap: Record<string, string> = {
    technical: `You are writing a technical changelog for engineers. Be precise. Mention affected systems, functions, or APIs where relevant. Readers are developers who want to know what changed and what might break.`,
    'plain-english': `You are writing a weekly engineering update for an engineering manager or team lead. Use plain English. Focus on what was completed, what moved forward, and what the team accomplished. No jargon.`,
    'benefit-focused': `You are writing product release notes for a product manager. Focus on features and improvements from a user or product perspective. Explain the benefit, not the implementation. Avoid technical terms.`,
    'marketing-friendly': `You are writing public-facing release notes for a marketing or growth team. Highlight new capabilities and improvements in customer-friendly language. Make it sound exciting but accurate. No technical details.`,
    friendly: `You are writing customer-facing release notes. Use friendly, clear language. Focus on what's new or better for the user. Keep it concise and positive.`,
  }

  const tone = toneMap[audience.tone] ?? `You are writing a changelog for the ${audience.id} audience with a ${audience.tone} tone.`

  return audience.description
    ? `${tone}\n\nAdditional context: ${audience.description}`
    : tone
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })
}

runAIPlugin(new AnthropicPlugin())