import { LinearClient } from '@linear/sdk'
import {
  OutputPlugin,
  DeliverRequest,
  DeliverResponse,
  getFinalContent,
  runOutputPlugin,
} from '@narratorlog/sdk'

interface LinearConfig {
  team_id: string
  token_env?: string
  label_name?: string
}

class LinearOutputPlugin implements OutputPlugin {
  async deliver(request: DeliverRequest): Promise<DeliverResponse> {
    const config = request.config as unknown as LinearConfig

    const tokenEnv = config.token_env ?? 'LINEAR_API_KEY'
    const token = process.env[tokenEnv]

    if (!token) {
      return { success: false, error: `${tokenEnv} environment variable not set` }
    }

    if (!config.team_id) {
      return { success: false, error: 'team_id is required in config' }
    }

    const content = getFinalContent(request)
    const client = new LinearClient({ apiKey: token })

    const from = new Date(request.scan.scan_from).toLocaleDateString('en-GB', {
      day: 'numeric', month: 'long', year: 'numeric',
    })
    const to = new Date(request.scan.scan_to).toLocaleDateString('en-GB', {
      day: 'numeric', month: 'long', year: 'numeric',
    })

    const title = `${request.scan.repository} — ${from} to ${to}`
    const body = `${content}\n\n---\n*Generated by narratorlog · narratorlog.dev*`

    try {
      const document = await client.createDocument({
        title,
        content: body,
        teamId: config.team_id,
      })

      const doc = await document.document

      return {
        success: true,
        reference: doc?.url ?? undefined,
        message: `Created Linear document: ${title}`,
      }
    } catch (err) {
      return { success: false, error: String(err) }
    }
  }
}

runOutputPlugin(new LinearOutputPlugin())