/** User-facing copy. API types and routes keep "scan" internally. */
export const copy = {
  story: 'Story',
  stories: 'Stories',
  runStory: 'Run story',
  runFirstStory: 'Run first story',
  storyQueued: 'Story queued.',
  storyFailed: "Couldn't start the story.",
  selectRepoToRun: 'Select a repository to run a story.',
  noStoriesYet: 'No stories yet. Connect a repository to begin.',
  noStoriesRun: 'No stories yet. Run one to read back what shipped.',
  recentStories: 'Recent stories',
  viewAllStories: 'View all',
  viewStory: 'View',
  viewStories: 'Stories',
  totalStories: 'Total stories',
  sent: 'Sent',
  needsReview: 'Needs review',
  awaitingReview: 'Awaiting your approval',
  neverRun: 'Not started',
  working: 'Working…',
  copyAll: 'Copy all',
  sendAll: 'Send all',
  copied: 'Copied to clipboard.',
} as const
