import {
  OutputPlugin,
  DeliverRequest,
  DeliverResponse,
  getFinalContent,
  runOutputPlugin,
} from '@narratorlog/sdk'

interface DiscordConfig {
  webhook_url_env?: string
  username?: string
  mention?: string
}

class DiscordOutputPlugin implements OutputPlugin {
  async deliver(request: DeliverRequest): Promise<DeliverResponse> {
    const config = request.config as unknown as DiscordConfig

    const webhookEnv = config.webhook_url_env ?? 'DISCORD_WEBHOOK_URL'
    const webhookUrl = process.env[webhookEnv]

    if (!webhookUrl) {
      return { success: false, error: `${webhookEnv} environment variable not set` }
    }

    const content = getFinalContent(request)
    const from = new Date(request.scan.scan_from).toLocaleDateString('en-GB')
    const to = new Date(request.scan.scan_to).toLocaleDateString('en-GB')

    const header = config.mention
      ? `${config.mention}\n**${request.scan.repository} — ${from} to ${to}**`
      : `**${request.scan.repository} — ${from} to ${to}**`

    // Discord has a 2000 char message limit — send in chunks
    const chunks = splitIntoChunks(content, 1800)
    const messages = [header + '\n\n' + chunks[0], ...chunks.slice(1)]
    const lastIndex = messages.length - 1
    messages[lastIndex] += '\n\n*Generated by narratorlog · narratorlog.dev*'

    try {
      for (const message of messages) {
        const response = await fetch(webhookUrl, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            content: message,
            username: config.username ?? 'narratorlog',
          }),
        })

        if (!response.ok) {
          const text = await response.text()
          return { success: false, error: `Discord webhook error: ${text}` }
        }
      }

      return {
        success: true,
        message: `Posted ${messages.length} message(s) to Discord`,
      }
    } catch (err) {
      return { success: false, error: String(err) }
    }
  }
}

function splitIntoChunks(text: string, maxLen: number): string[] {
  if (text.length <= maxLen) return [text]

  const chunks: string[] = []
  const lines = text.split('\n')
  let current = ''

  for (const line of lines) {
    if ((current + '\n' + line).length > maxLen) {
      if (current) chunks.push(current.trim())
      current = line
    } else {
      current = current ? current + '\n' + line : line
    }
  }

  if (current.trim()) chunks.push(current.trim())
  return chunks
}

runOutputPlugin(new DiscordOutputPlugin())