version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: narratorlog
      POSTGRES_USER: narratorlog
      POSTGRES_PASSWORD: narratorlog
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data: