// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audience_drafts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const allDraftsApproved = `-- name: AllDraftsApproved :one
SELECT COUNT(*) FILTER (WHERE status != 'approved') = 0 AS all_approved
FROM audience_drafts
WHERE scan_id = $1
`

func (q *Queries) AllDraftsApproved(ctx context.Context, scanID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, allDraftsApproved, scanID)
	var all_approved bool
	err := row.Scan(&all_approved)
	return all_approved, err
}

const approveDraft = `-- name: ApproveDraft :one
UPDATE audience_drafts
SET
  status      = 'approved',
  approved_by = $1,
  approved_at = now(),
  updated_at  = now()
WHERE id = $2
RETURNING id, scan_id, audience_id, tone, content, edited_content, status, approved_by, approved_at, created_at, updated_at
`

type ApproveDraftParams struct {
	ApprovedBy pgtype.UUID `json:"approved_by"`
	ID         uuid.UUID   `json:"id"`
}

func (q *Queries) ApproveDraft(ctx context.Context, arg ApproveDraftParams) (AudienceDraft, error) {
	row := q.db.QueryRow(ctx, approveDraft, arg.ApprovedBy, arg.ID)
	var i AudienceDraft
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.AudienceID,
		&i.Tone,
		&i.Content,
		&i.EditedContent,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countPendingDraftsByScan = `-- name: CountPendingDraftsByScan :one
SELECT COUNT(*) FROM audience_drafts
WHERE scan_id = $1 AND status = 'draft'
`

func (q *Queries) CountPendingDraftsByScan(ctx context.Context, scanID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingDraftsByScan, scanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAudienceDraft = `-- name: CreateAudienceDraft :one
INSERT INTO audience_drafts (scan_id, audience_id, tone, content)
VALUES ($1, $2, $3, $4)
RETURNING id, scan_id, audience_id, tone, content, edited_content, status, approved_by, approved_at, created_at, updated_at
`

type CreateAudienceDraftParams struct {
	ScanID     uuid.UUID `json:"scan_id"`
	AudienceID string    `json:"audience_id"`
	Tone       string    `json:"tone"`
	Content    string    `json:"content"`
}

func (q *Queries) CreateAudienceDraft(ctx context.Context, arg CreateAudienceDraftParams) (AudienceDraft, error) {
	row := q.db.QueryRow(ctx, createAudienceDraft,
		arg.ScanID,
		arg.AudienceID,
		arg.Tone,
		arg.Content,
	)
	var i AudienceDraft
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.AudienceID,
		&i.Tone,
		&i.Content,
		&i.EditedContent,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDraftByID = `-- name: GetDraftByID :one
SELECT id, scan_id, audience_id, tone, content, edited_content, status, approved_by, approved_at, created_at, updated_at FROM audience_drafts WHERE id = $1
`

func (q *Queries) GetDraftByID(ctx context.Context, id uuid.UUID) (AudienceDraft, error) {
	row := q.db.QueryRow(ctx, getDraftByID, id)
	var i AudienceDraft
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.AudienceID,
		&i.Tone,
		&i.Content,
		&i.EditedContent,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDraftsByScan = `-- name: ListDraftsByScan :many
SELECT id, scan_id, audience_id, tone, content, edited_content, status, approved_by, approved_at, created_at, updated_at FROM audience_drafts
WHERE scan_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListDraftsByScan(ctx context.Context, scanID uuid.UUID) ([]AudienceDraft, error) {
	rows, err := q.db.Query(ctx, listDraftsByScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AudienceDraft
	for rows.Next() {
		var i AudienceDraft
		if err := rows.Scan(
			&i.ID,
			&i.ScanID,
			&i.AudienceID,
			&i.Tone,
			&i.Content,
			&i.EditedContent,
			&i.Status,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDraftDelivered = `-- name: MarkDraftDelivered :exec
UPDATE audience_drafts
SET status = 'delivered', updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkDraftDelivered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDraftDelivered, id)
	return err
}

const rejectDraft = `-- name: RejectDraft :one
UPDATE audience_drafts
SET status = 'rejected', updated_at = now()
WHERE id = $1
RETURNING id, scan_id, audience_id, tone, content, edited_content, status, approved_by, approved_at, created_at, updated_at
`

func (q *Queries) RejectDraft(ctx context.Context, id uuid.UUID) (AudienceDraft, error) {
	row := q.db.QueryRow(ctx, rejectDraft, id)
	var i AudienceDraft
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.AudienceID,
		&i.Tone,
		&i.Content,
		&i.EditedContent,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDraftContent = `-- name: UpdateDraftContent :one
UPDATE audience_drafts
SET edited_content = $1, updated_at = now()
WHERE id = $2
RETURNING id, scan_id, audience_id, tone, content, edited_content, status, approved_by, approved_at, created_at, updated_at
`

type UpdateDraftContentParams struct {
	EditedContent pgtype.Text `json:"edited_content"`
	ID            uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateDraftContent(ctx context.Context, arg UpdateDraftContentParams) (AudienceDraft, error) {
	row := q.db.QueryRow(ctx, updateDraftContent, arg.EditedContent, arg.ID)
	var i AudienceDraft
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.AudienceID,
		&i.Tone,
		&i.Content,
		&i.EditedContent,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
