// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commits.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCommit = `-- name: CreateCommit :one
INSERT INTO commits (
  scan_id, repository_id, sha, message, author_name, author_email,
  committed_at, pr_number, pr_title, pr_description, linked_issues,
  changed_files, diff, is_noise, is_bot, is_breaking, domain
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, scan_id, repository_id, sha, message, author_name, author_email, committed_at, pr_number, pr_title, pr_description, linked_issues, changed_files, diff, codebase_context, is_noise, is_bot, is_breaking, domain, created_at
`

type CreateCommitParams struct {
	ScanID        uuid.UUID          `json:"scan_id"`
	RepositoryID  uuid.UUID          `json:"repository_id"`
	Sha           string             `json:"sha"`
	Message       string             `json:"message"`
	AuthorName    string             `json:"author_name"`
	AuthorEmail   string             `json:"author_email"`
	CommittedAt   pgtype.Timestamptz `json:"committed_at"`
	PrNumber      pgtype.Int4        `json:"pr_number"`
	PrTitle       pgtype.Text        `json:"pr_title"`
	PrDescription pgtype.Text        `json:"pr_description"`
	LinkedIssues  []byte             `json:"linked_issues"`
	ChangedFiles  []byte             `json:"changed_files"`
	Diff          pgtype.Text        `json:"diff"`
	IsNoise       bool               `json:"is_noise"`
	IsBot         bool               `json:"is_bot"`
	IsBreaking    bool               `json:"is_breaking"`
	Domain        pgtype.Text        `json:"domain"`
}

func (q *Queries) CreateCommit(ctx context.Context, arg CreateCommitParams) (Commit, error) {
	row := q.db.QueryRow(ctx, createCommit,
		arg.ScanID,
		arg.RepositoryID,
		arg.Sha,
		arg.Message,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.CommittedAt,
		arg.PrNumber,
		arg.PrTitle,
		arg.PrDescription,
		arg.LinkedIssues,
		arg.ChangedFiles,
		arg.Diff,
		arg.IsNoise,
		arg.IsBot,
		arg.IsBreaking,
		arg.Domain,
	)
	var i Commit
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.RepositoryID,
		&i.Sha,
		&i.Message,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.CommittedAt,
		&i.PrNumber,
		&i.PrTitle,
		&i.PrDescription,
		&i.LinkedIssues,
		&i.ChangedFiles,
		&i.Diff,
		&i.CodebaseContext,
		&i.IsNoise,
		&i.IsBot,
		&i.IsBreaking,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const createCommitIgnoreDuplicate = `-- name: CreateCommitIgnoreDuplicate :exec
INSERT INTO commits (
  scan_id, repository_id, sha, message, author_name, author_email,
  committed_at, pr_number, pr_title, pr_description, linked_issues,
  changed_files, diff, is_noise, is_bot, is_breaking, domain
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
ON CONFLICT (scan_id, sha) DO NOTHING
`

func (q *Queries) CreateCommitIgnoreDuplicate(ctx context.Context, arg CreateCommitParams) error {
	_, err := q.db.Exec(ctx, createCommitIgnoreDuplicate,
		arg.ScanID,
		arg.RepositoryID,
		arg.Sha,
		arg.Message,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.CommittedAt,
		arg.PrNumber,
		arg.PrTitle,
		arg.PrDescription,
		arg.LinkedIssues,
		arg.ChangedFiles,
		arg.Diff,
		arg.IsNoise,
		arg.IsBot,
		arg.IsBreaking,
		arg.Domain,
	)
	return err
}

const getCommitSHAsByScan = `-- name: GetCommitSHAsByScan :many
SELECT sha FROM commits WHERE scan_id = $1
`

func (q *Queries) GetCommitSHAsByScan(ctx context.Context, scanID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getCommitSHAsByScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var sha string
		if err := rows.Scan(&sha); err != nil {
			return nil, err
		}
		items = append(items, sha)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKnownSHAsByRepository = `-- name: GetKnownSHAsByRepository :many
SELECT DISTINCT sha FROM commits
WHERE repository_id = $1
`

func (q *Queries) GetKnownSHAsByRepository(ctx context.Context, repositoryID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getKnownSHAsByRepository, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var sha string
		if err := rows.Scan(&sha); err != nil {
			return nil, err
		}
		items = append(items, sha)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCommitsByScan = `-- name: ListAllCommitsByScan :many
SELECT id, scan_id, repository_id, sha, message, author_name, author_email, committed_at, pr_number, pr_title, pr_description, linked_issues, changed_files, diff, codebase_context, is_noise, is_bot, is_breaking, domain, created_at FROM commits
WHERE scan_id = $1
ORDER BY committed_at ASC
`

func (q *Queries) ListAllCommitsByScan(ctx context.Context, scanID uuid.UUID) ([]Commit, error) {
	rows, err := q.db.Query(ctx, listAllCommitsByScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commit
	for rows.Next() {
		var i Commit
		if err := rows.Scan(
			&i.ID,
			&i.ScanID,
			&i.RepositoryID,
			&i.Sha,
			&i.Message,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.CommittedAt,
			&i.PrNumber,
			&i.PrTitle,
			&i.PrDescription,
			&i.LinkedIssues,
			&i.ChangedFiles,
			&i.Diff,
			&i.CodebaseContext,
			&i.IsNoise,
			&i.IsBot,
			&i.IsBreaking,
			&i.Domain,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommitsByScan = `-- name: ListCommitsByScan :many
SELECT id, scan_id, repository_id, sha, message, author_name, author_email, committed_at, pr_number, pr_title, pr_description, linked_issues, changed_files, diff, codebase_context, is_noise, is_bot, is_breaking, domain, created_at FROM commits
WHERE scan_id = $1 AND is_noise = false
ORDER BY committed_at ASC
`

func (q *Queries) ListCommitsByScan(ctx context.Context, scanID uuid.UUID) ([]Commit, error) {
	rows, err := q.db.Query(ctx, listCommitsByScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commit
	for rows.Next() {
		var i Commit
		if err := rows.Scan(
			&i.ID,
			&i.ScanID,
			&i.RepositoryID,
			&i.Sha,
			&i.Message,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.CommittedAt,
			&i.PrNumber,
			&i.PrTitle,
			&i.PrDescription,
			&i.LinkedIssues,
			&i.ChangedFiles,
			&i.Diff,
			&i.CodebaseContext,
			&i.IsNoise,
			&i.IsBot,
			&i.IsBreaking,
			&i.Domain,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommitContext = `-- name: UpdateCommitContext :exec
UPDATE commits
SET codebase_context = $1
WHERE id = $2
`

type UpdateCommitContextParams struct {
	CodebaseContext []byte    `json:"codebase_context"`
	ID              uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCommitContext(ctx context.Context, arg UpdateCommitContextParams) error {
	_, err := q.db.Exec(ctx, updateCommitContext, arg.CodebaseContext, arg.ID)
	return err
}

const updateCommitEnrichment = `-- name: UpdateCommitEnrichment :exec
UPDATE commits
SET
  pr_title       = $1,
  pr_description = $2,
  linked_issues  = $3,
  is_breaking    = $4,
  domain         = $5
WHERE id = $6
`

type UpdateCommitEnrichmentParams struct {
	PrTitle       pgtype.Text `json:"pr_title"`
	PrDescription pgtype.Text `json:"pr_description"`
	LinkedIssues  []byte      `json:"linked_issues"`
	IsBreaking    bool        `json:"is_breaking"`
	Domain        pgtype.Text `json:"domain"`
	ID            uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateCommitEnrichment(ctx context.Context, arg UpdateCommitEnrichmentParams) error {
	_, err := q.db.Exec(ctx, updateCommitEnrichment,
		arg.PrTitle,
		arg.PrDescription,
		arg.LinkedIssues,
		arg.IsBreaking,
		arg.Domain,
		arg.ID,
	)
	return err
}
