// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commit_groups.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createCommitGroup = `-- name: CreateCommitGroup :one
INSERT INTO commit_groups (scan_id, label, commit_ids, group_type)
VALUES ($1, $2, $3, $4)
RETURNING id, scan_id, label, commit_ids, group_type, summary, created_at
`

type CreateCommitGroupParams struct {
	ScanID    uuid.UUID   `json:"scan_id"`
	Label     string      `json:"label"`
	CommitIds []uuid.UUID `json:"commit_ids"`
	GroupType GroupType   `json:"group_type"`
}

func (q *Queries) CreateCommitGroup(ctx context.Context, arg CreateCommitGroupParams) (CommitGroup, error) {
	row := q.db.QueryRowContext(ctx, createCommitGroup,
		arg.ScanID,
		arg.Label,
		pq.Array(arg.CommitIds),
		arg.GroupType,
	)
	var i CommitGroup
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.Label,
		pq.Array(&i.CommitIds),
		&i.GroupType,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}

const listCommitGroupsByScan = `-- name: ListCommitGroupsByScan :many
SELECT id, scan_id, label, commit_ids, group_type, summary, created_at FROM commit_groups
WHERE scan_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCommitGroupsByScan(ctx context.Context, scanID uuid.UUID) ([]CommitGroup, error) {
	rows, err := q.db.QueryContext(ctx, listCommitGroupsByScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommitGroup
	for rows.Next() {
		var i CommitGroup
		if err := rows.Scan(
			&i.ID,
			&i.ScanID,
			&i.Label,
			pq.Array(&i.CommitIds),
			&i.GroupType,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommitGroupSummary = `-- name: UpdateCommitGroupSummary :exec
UPDATE commit_groups
SET summary = $1
WHERE id = $2
`

type UpdateCommitGroupSummaryParams struct {
	Summary sql.NullString `json:"summary"`
	ID      uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateCommitGroupSummary(ctx context.Context, arg UpdateCommitGroupSummaryParams) error {
	_, err := q.db.ExecContext(ctx, updateCommitGroupSummary, arg.Summary, arg.ID)
	return err
}
