// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO deliveries (draft_id, output_plugin)
VALUES ($1, $2)
RETURNING id, draft_id, output_plugin, status, response, attempt_count, delivered_at, created_at, updated_at
`

type CreateDeliveryParams struct {
	DraftID      uuid.UUID `json:"draft_id"`
	OutputPlugin string    `json:"output_plugin"`
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, createDelivery, arg.DraftID, arg.OutputPlugin)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.OutputPlugin,
		&i.Status,
		&i.Response,
		&i.AttemptCount,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeliveriesByDraft = `-- name: ListDeliveriesByDraft :many
SELECT id, draft_id, output_plugin, status, response, attempt_count, delivered_at, created_at, updated_at FROM deliveries
WHERE draft_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListDeliveriesByDraft(ctx context.Context, draftID uuid.UUID) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesByDraft, draftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.DraftID,
			&i.OutputPlugin,
			&i.Status,
			&i.Response,
			&i.AttemptCount,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveriesByScan = `-- name: ListDeliveriesByScan :many
SELECT
  d.id,
  d.draft_id,
  d.output_plugin,
  d.status,
  d.response,
  d.attempt_count,
  d.delivered_at,
  d.created_at,
  d.updated_at,
  ad.audience_id
FROM deliveries d
INNER JOIN audience_drafts ad ON ad.id = d.draft_id
WHERE ad.scan_id = $1
ORDER BY d.created_at ASC
`

type ListDeliveriesByScanRow struct {
	ID           uuid.UUID          `json:"id"`
	DraftID      uuid.UUID          `json:"draft_id"`
	OutputPlugin string             `json:"output_plugin"`
	Status       DeliveryStatus     `json:"status"`
	Response     []byte             `json:"response"`
	AttemptCount int32              `json:"attempt_count"`
	DeliveredAt  pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	AudienceID   string             `json:"audience_id"`
}

func (q *Queries) ListDeliveriesByScan(ctx context.Context, scanID uuid.UUID) ([]ListDeliveriesByScanRow, error) {
	rows, err := q.db.Query(ctx, listDeliveriesByScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeliveriesByScanRow
	for rows.Next() {
		var i ListDeliveriesByScanRow
		if err := rows.Scan(
			&i.ID,
			&i.DraftID,
			&i.OutputPlugin,
			&i.Status,
			&i.Response,
			&i.AttemptCount,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AudienceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeliveryFailed = `-- name: UpdateDeliveryFailed :exec
UPDATE deliveries
SET
  status        = 'failed',
  response      = $1,
  attempt_count = attempt_count + 1,
  updated_at    = now()
WHERE id = $2
`

type UpdateDeliveryFailedParams struct {
	Response []byte    `json:"response"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateDeliveryFailed(ctx context.Context, arg UpdateDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, updateDeliveryFailed, arg.Response, arg.ID)
	return err
}

const updateDeliverySuccess = `-- name: UpdateDeliverySuccess :exec
UPDATE deliveries
SET
  status       = 'success',
  response     = $1,
  delivered_at = now(),
  attempt_count = attempt_count + 1,
  updated_at   = now()
WHERE id = $2
`

type UpdateDeliverySuccessParams struct {
	Response []byte    `json:"response"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateDeliverySuccess(ctx context.Context, arg UpdateDeliverySuccessParams) error {
	_, err := q.db.Exec(ctx, updateDeliverySuccess, arg.Response, arg.ID)
	return err
}
