// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: draft_comments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDraftComment = `-- name: CreateDraftComment :one
INSERT INTO draft_comments (draft_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, draft_id, user_id, content, created_at
`

type CreateDraftCommentParams struct {
	DraftID uuid.UUID `json:"draft_id"`
	UserID  uuid.UUID `json:"user_id"`
	Content string    `json:"content"`
}

func (q *Queries) CreateDraftComment(ctx context.Context, arg CreateDraftCommentParams) (DraftComment, error) {
	row := q.db.QueryRow(ctx, createDraftComment, arg.DraftID, arg.UserID, arg.Content)
	var i DraftComment
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDraftComment = `-- name: DeleteDraftComment :exec
DELETE FROM draft_comments
WHERE id = $1 AND user_id = $2
`

type DeleteDraftCommentParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDraftComment(ctx context.Context, arg DeleteDraftCommentParams) error {
	_, err := q.db.Exec(ctx, deleteDraftComment, arg.ID, arg.UserID)
	return err
}

const listCommentsByDraft = `-- name: ListCommentsByDraft :many
SELECT
  dc.id, dc.draft_id, dc.user_id, dc.content, dc.created_at,
  u.name  AS user_name,
  u.avatar_url AS user_avatar
FROM draft_comments dc
JOIN users u ON u.id = dc.user_id
WHERE dc.draft_id = $1
ORDER BY dc.created_at ASC
`

type ListCommentsByDraftRow struct {
	ID         uuid.UUID          `json:"id"`
	DraftID    uuid.UUID          `json:"draft_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UserName   string             `json:"user_name"`
	UserAvatar pgtype.Text        `json:"user_avatar"`
}

func (q *Queries) ListCommentsByDraft(ctx context.Context, draftID uuid.UUID) ([]ListCommentsByDraftRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByDraft, draftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByDraftRow
	for rows.Next() {
		var i ListCommentsByDraftRow
		if err := rows.Scan(
			&i.ID,
			&i.DraftID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UserName,
			&i.UserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
