// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type DeliveryStatus string

const (
	DeliveryStatusPending DeliveryStatus = "pending"
	DeliveryStatusSuccess DeliveryStatus = "success"
	DeliveryStatusFailed  DeliveryStatus = "failed"
)

func (e *DeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryStatus(s)
	case string:
		*e = DeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryStatus: %T", src)
	}
	return nil
}

type NullDeliveryStatus struct {
	DeliveryStatus DeliveryStatus `json:"delivery_status"`
	Valid          bool           `json:"valid"` // Valid is true if DeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryStatus), nil
}

type DraftStatus string

const (
	DraftStatusDraft     DraftStatus = "draft"
	DraftStatusApproved  DraftStatus = "approved"
	DraftStatusRejected  DraftStatus = "rejected"
	DraftStatusDelivered DraftStatus = "delivered"
)

func (e *DraftStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DraftStatus(s)
	case string:
		*e = DraftStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DraftStatus: %T", src)
	}
	return nil
}

type NullDraftStatus struct {
	DraftStatus DraftStatus `json:"draft_status"`
	Valid       bool        `json:"valid"` // Valid is true if DraftStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDraftStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DraftStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DraftStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDraftStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DraftStatus), nil
}

type GitProvider string

const (
	GitProviderGithub    GitProvider = "github"
	GitProviderGitlab    GitProvider = "gitlab"
	GitProviderBitbucket GitProvider = "bitbucket"
	GitProviderGitCli    GitProvider = "git_cli"
)

func (e *GitProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GitProvider(s)
	case string:
		*e = GitProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for GitProvider: %T", src)
	}
	return nil
}

type NullGitProvider struct {
	GitProvider GitProvider `json:"git_provider"`
	Valid       bool        `json:"valid"` // Valid is true if GitProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGitProvider) Scan(value interface{}) error {
	if value == nil {
		ns.GitProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GitProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGitProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GitProvider), nil
}

type GroupType string

const (
	GroupTypeFeature  GroupType = "feature"
	GroupTypeFix      GroupType = "fix"
	GroupTypeBreaking GroupType = "breaking"
	GroupTypeChore    GroupType = "chore"
	GroupTypeSecurity GroupType = "security"
	GroupTypeOther    GroupType = "other"
)

func (e *GroupType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupType(s)
	case string:
		*e = GroupType(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupType: %T", src)
	}
	return nil
}

type NullGroupType struct {
	GroupType GroupType `json:"group_type"`
	Valid     bool      `json:"valid"` // Valid is true if GroupType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupType) Scan(value interface{}) error {
	if value == nil {
		ns.GroupType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupType), nil
}

type ScanStatus string

const (
	ScanStatusPending          ScanStatus = "pending"
	ScanStatusRunning          ScanStatus = "running"
	ScanStatusFiltering        ScanStatus = "filtering"
	ScanStatusEnriching        ScanStatus = "enriching"
	ScanStatusReadingContext   ScanStatus = "reading_context"
	ScanStatusChunking         ScanStatus = "chunking"
	ScanStatusSummarizing      ScanStatus = "summarizing"
	ScanStatusAwaitingApproval ScanStatus = "awaiting_approval"
	ScanStatusApproved         ScanStatus = "approved"
	ScanStatusDelivering       ScanStatus = "delivering"
	ScanStatusDelivered        ScanStatus = "delivered"
	ScanStatusFailed           ScanStatus = "failed"
	ScanStatusCancelled        ScanStatus = "cancelled"
)

func (e *ScanStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScanStatus(s)
	case string:
		*e = ScanStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ScanStatus: %T", src)
	}
	return nil
}

type NullScanStatus struct {
	ScanStatus ScanStatus `json:"scan_status"`
	Valid      bool       `json:"valid"` // Valid is true if ScanStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScanStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ScanStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScanStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScanStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScanStatus), nil
}

type ScanTrigger string

const (
	ScanTriggerScheduled ScanTrigger = "scheduled"
	ScanTriggerManual    ScanTrigger = "manual"
	ScanTriggerWebhook   ScanTrigger = "webhook"
	ScanTriggerCli       ScanTrigger = "cli"
)

func (e *ScanTrigger) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScanTrigger(s)
	case string:
		*e = ScanTrigger(s)
	default:
		return fmt.Errorf("unsupported scan type for ScanTrigger: %T", src)
	}
	return nil
}

type NullScanTrigger struct {
	ScanTrigger ScanTrigger `json:"scan_trigger"`
	Valid       bool        `json:"valid"` // Valid is true if ScanTrigger is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScanTrigger) Scan(value interface{}) error {
	if value == nil {
		ns.ScanTrigger, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScanTrigger.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScanTrigger) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScanTrigger), nil
}

type UserRole string

const (
	UserRoleAdmin    UserRole = "admin"
	UserRoleReviewer UserRole = "reviewer"
	UserRoleViewer   UserRole = "viewer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AudienceDraft struct {
	ID            uuid.UUID      `json:"id"`
	ScanID        uuid.UUID      `json:"scan_id"`
	AudienceID    string         `json:"audience_id"`
	Tone          string         `json:"tone"`
	Content       string         `json:"content"`
	EditedContent sql.NullString `json:"edited_content"`
	Status        DraftStatus    `json:"status"`
	ApprovedBy    uuid.NullUUID  `json:"approved_by"`
	ApprovedAt    sql.NullTime   `json:"approved_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type AuditLog struct {
	ID         uuid.UUID       `json:"id"`
	TeamID     uuid.UUID       `json:"team_id"`
	UserID     uuid.NullUUID   `json:"user_id"`
	Action     string          `json:"action"`
	EntityType string          `json:"entity_type"`
	EntityID   uuid.NullUUID   `json:"entity_id"`
	Metadata   json.RawMessage `json:"metadata"`
	CreatedAt  time.Time       `json:"created_at"`
}

type Commit struct {
	ID              uuid.UUID             `json:"id"`
	ScanID          uuid.UUID             `json:"scan_id"`
	RepositoryID    uuid.UUID             `json:"repository_id"`
	Sha             string                `json:"sha"`
	Message         string                `json:"message"`
	AuthorName      string                `json:"author_name"`
	AuthorEmail     string                `json:"author_email"`
	CommittedAt     time.Time             `json:"committed_at"`
	PrNumber        sql.NullInt32         `json:"pr_number"`
	PrTitle         sql.NullString        `json:"pr_title"`
	PrDescription   sql.NullString        `json:"pr_description"`
	LinkedIssues    json.RawMessage       `json:"linked_issues"`
	ChangedFiles    json.RawMessage       `json:"changed_files"`
	Diff            sql.NullString        `json:"diff"`
	CodebaseContext pqtype.NullRawMessage `json:"codebase_context"`
	IsNoise         bool                  `json:"is_noise"`
	IsBot           bool                  `json:"is_bot"`
	IsBreaking      bool                  `json:"is_breaking"`
	Domain          sql.NullString        `json:"domain"`
	CreatedAt       time.Time             `json:"created_at"`
}

type CommitGroup struct {
	ID        uuid.UUID      `json:"id"`
	ScanID    uuid.UUID      `json:"scan_id"`
	Label     string         `json:"label"`
	CommitIds []uuid.UUID    `json:"commit_ids"`
	GroupType GroupType      `json:"group_type"`
	Summary   sql.NullString `json:"summary"`
	CreatedAt time.Time      `json:"created_at"`
}

type Delivery struct {
	ID           uuid.UUID             `json:"id"`
	DraftID      uuid.UUID             `json:"draft_id"`
	OutputPlugin string                `json:"output_plugin"`
	Status       DeliveryStatus        `json:"status"`
	Response     pqtype.NullRawMessage `json:"response"`
	AttemptCount int32                 `json:"attempt_count"`
	DeliveredAt  sql.NullTime          `json:"delivered_at"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
}

type DraftComment struct {
	ID        uuid.UUID `json:"id"`
	DraftID   uuid.UUID `json:"draft_id"`
	UserID    uuid.UUID `json:"user_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type Repository struct {
	ID            uuid.UUID       `json:"id"`
	TeamID        uuid.UUID       `json:"team_id"`
	Provider      GitProvider     `json:"provider"`
	ProviderID    string          `json:"provider_id"`
	Name          string          `json:"name"`
	FullName      string          `json:"full_name"`
	Url           string          `json:"url"`
	DefaultBranch string          `json:"default_branch"`
	AccessToken   string          `json:"access_token"`
	WebhookSecret sql.NullString  `json:"webhook_secret"`
	Config        json.RawMessage `json:"config"`
	IsActive      bool            `json:"is_active"`
	LastScannedAt sql.NullTime    `json:"last_scanned_at"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type Scan struct {
	ID                uuid.UUID       `json:"id"`
	TeamID            uuid.UUID       `json:"team_id"`
	RepositoryID      uuid.UUID       `json:"repository_id"`
	Status            ScanStatus      `json:"status"`
	TriggeredBy       ScanTrigger     `json:"triggered_by"`
	TriggeredByUserID uuid.NullUUID   `json:"triggered_by_user_id"`
	ScanFrom          time.Time       `json:"scan_from"`
	ScanTo            time.Time       `json:"scan_to"`
	CommitCount       int32           `json:"commit_count"`
	FilteredCount     int32           `json:"filtered_count"`
	Error             sql.NullString  `json:"error"`
	ConfigSnapshot    json.RawMessage `json:"config_snapshot"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Team struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID         uuid.UUID      `json:"id"`
	TeamID     uuid.UUID      `json:"team_id"`
	Email      string         `json:"email"`
	Name       string         `json:"name"`
	AvatarUrl  sql.NullString `json:"avatar_url"`
	Role       UserRole       `json:"role"`
	Provider   string         `json:"provider"`
	ProviderID string         `json:"provider_id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}
