// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AllDraftsApproved(ctx context.Context, scanID uuid.UUID) (bool, error)
	ApproveDraft(ctx context.Context, arg ApproveDraftParams) (AudienceDraft, error)
	CountPendingApprovalsByTeam(ctx context.Context, teamID uuid.UUID) (int64, error)
	CountPendingDraftsByScan(ctx context.Context, scanID uuid.UUID) (int64, error)
	CreateAudienceDraft(ctx context.Context, arg CreateAudienceDraftParams) (AudienceDraft, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateCommit(ctx context.Context, arg CreateCommitParams) (Commit, error)
	CreateCommitIgnoreDuplicate(ctx context.Context, arg CreateCommitParams) error
	CreateCommitGroup(ctx context.Context, arg CreateCommitGroupParams) (CommitGroup, error)
	CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error)
	CreateDraftComment(ctx context.Context, arg CreateDraftCommentParams) (DraftComment, error)
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error)
	CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateTeamWithSetup(ctx context.Context, arg CreateTeamWithSetupParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (User, error)
	DeactivateRepository(ctx context.Context, id uuid.UUID) error
	DeleteDraftComment(ctx context.Context, arg DeleteDraftCommentParams) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, tokenHash string) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserSessions(ctx context.Context, userID uuid.UUID) error
	GetCommitSHAsByScan(ctx context.Context, scanID uuid.UUID) ([]string, error)
	GetDraftByID(ctx context.Context, id uuid.UUID) (AudienceDraft, error)
	GetKnownSHAsByRepository(ctx context.Context, repositoryID uuid.UUID) ([]string, error)
	GetRepositoryByID(ctx context.Context, id uuid.UUID) (Repository, error)
	GetRepositoryByProviderID(ctx context.Context, arg GetRepositoryByProviderIDParams) (Repository, error)
	GetScanByID(ctx context.Context, id uuid.UUID) (Scan, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error)
	GetTeamBySlug(ctx context.Context, slug string) (Team, error)
	GetTeamConfig(ctx context.Context, id uuid.UUID) ([]byte, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailWithPassword(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (User, error)
	IsSetupComplete(ctx context.Context) (bool, error)
	ListActiveWeeklyRepos(ctx context.Context) ([]Repository, error)
	ListAllCommitsByScan(ctx context.Context, scanID uuid.UUID) ([]Commit, error)
	ListAuditLogByEntity(ctx context.Context, arg ListAuditLogByEntityParams) ([]AuditLog, error)
	ListAuditLogByTeam(ctx context.Context, arg ListAuditLogByTeamParams) ([]AuditLog, error)
	ListCommentsByDraft(ctx context.Context, draftID uuid.UUID) ([]ListCommentsByDraftRow, error)
	ListCommitGroupsByScan(ctx context.Context, scanID uuid.UUID) ([]CommitGroup, error)
	ListCommitsByScan(ctx context.Context, scanID uuid.UUID) ([]Commit, error)
	ListDeliveriesByDraft(ctx context.Context, draftID uuid.UUID) ([]Delivery, error)
	ListDraftsByScan(ctx context.Context, scanID uuid.UUID) ([]AudienceDraft, error)
	ListRepositoriesByTeam(ctx context.Context, teamID uuid.UUID) ([]Repository, error)
	ListScansByRepository(ctx context.Context, arg ListScansByRepositoryParams) ([]Scan, error)
	ListScansByTeam(ctx context.Context, arg ListScansByTeamParams) ([]Scan, error)
	ListUsersByTeam(ctx context.Context, teamID uuid.UUID) ([]User, error)
	MarkDraftDelivered(ctx context.Context, id uuid.UUID) error
	MarkSetupComplete(ctx context.Context, id uuid.UUID) error
	RejectDraft(ctx context.Context, id uuid.UUID) (AudienceDraft, error)
	UpdateCommitContext(ctx context.Context, arg UpdateCommitContextParams) error
	UpdateCommitEnrichment(ctx context.Context, arg UpdateCommitEnrichmentParams) error
	UpdateCommitGroupSummary(ctx context.Context, arg UpdateCommitGroupSummaryParams) error
	UpdateDeliveryFailed(ctx context.Context, arg UpdateDeliveryFailedParams) error
	UpdateDeliverySuccess(ctx context.Context, arg UpdateDeliverySuccessParams) error
	UpdateDraftContent(ctx context.Context, arg UpdateDraftContentParams) (AudienceDraft, error)
	UpdateRepositoryConfig(ctx context.Context, arg UpdateRepositoryConfigParams) (Repository, error)
	UpdateRepositoryLastScanned(ctx context.Context, id uuid.UUID) error
	UpdateScanCounts(ctx context.Context, arg UpdateScanCountsParams) error
	UpdateScanStatus(ctx context.Context, arg UpdateScanStatusParams) error
	UpdateScanStatusWithError(ctx context.Context, arg UpdateScanStatusWithErrorParams) error
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateTeamConfig(ctx context.Context, arg UpdateTeamConfigParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
