// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repositories.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (
  team_id, provider, provider_id, name, full_name,
  url, default_branch, access_token, webhook_secret, config
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, team_id, provider, provider_id, name, full_name, url, default_branch, access_token, webhook_secret, config, is_active, last_scanned_at, created_at, updated_at
`

type CreateRepositoryParams struct {
	TeamID        uuid.UUID   `json:"team_id"`
	Provider      GitProvider `json:"provider"`
	ProviderID    string      `json:"provider_id"`
	Name          string      `json:"name"`
	FullName      string      `json:"full_name"`
	Url           string      `json:"url"`
	DefaultBranch string      `json:"default_branch"`
	AccessToken   string      `json:"access_token"`
	WebhookSecret pgtype.Text `json:"webhook_secret"`
	Config        []byte      `json:"config"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository,
		arg.TeamID,
		arg.Provider,
		arg.ProviderID,
		arg.Name,
		arg.FullName,
		arg.Url,
		arg.DefaultBranch,
		arg.AccessToken,
		arg.WebhookSecret,
		arg.Config,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.ProviderID,
		&i.Name,
		&i.FullName,
		&i.Url,
		&i.DefaultBranch,
		&i.AccessToken,
		&i.WebhookSecret,
		&i.Config,
		&i.IsActive,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateRepository = `-- name: DeactivateRepository :exec
UPDATE repositories
SET is_active = false, updated_at = now()
WHERE id = $1
`

func (q *Queries) DeactivateRepository(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateRepository, id)
	return err
}

const getRepositoryByID = `-- name: GetRepositoryByID :one
SELECT id, team_id, provider, provider_id, name, full_name, url, default_branch, access_token, webhook_secret, config, is_active, last_scanned_at, created_at, updated_at FROM repositories
WHERE id = $1
`

func (q *Queries) GetRepositoryByID(ctx context.Context, id uuid.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByID, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.ProviderID,
		&i.Name,
		&i.FullName,
		&i.Url,
		&i.DefaultBranch,
		&i.AccessToken,
		&i.WebhookSecret,
		&i.Config,
		&i.IsActive,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByProviderID = `-- name: GetRepositoryByProviderID :one
SELECT id, team_id, provider, provider_id, name, full_name, url, default_branch, access_token, webhook_secret, config, is_active, last_scanned_at, created_at, updated_at FROM repositories
WHERE team_id = $1 AND provider = $2 AND provider_id = $3
`

type GetRepositoryByProviderIDParams struct {
	TeamID     uuid.UUID   `json:"team_id"`
	Provider   GitProvider `json:"provider"`
	ProviderID string      `json:"provider_id"`
}

func (q *Queries) GetRepositoryByProviderID(ctx context.Context, arg GetRepositoryByProviderIDParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByProviderID, arg.TeamID, arg.Provider, arg.ProviderID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.ProviderID,
		&i.Name,
		&i.FullName,
		&i.Url,
		&i.DefaultBranch,
		&i.AccessToken,
		&i.WebhookSecret,
		&i.Config,
		&i.IsActive,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositoriesByTeam = `-- name: ListRepositoriesByTeam :many
SELECT id, team_id, provider, provider_id, name, full_name, url, default_branch, access_token, webhook_secret, config, is_active, last_scanned_at, created_at, updated_at FROM repositories
WHERE team_id = $1 AND is_active = true
ORDER BY created_at ASC
`

func (q *Queries) ListRepositoriesByTeam(ctx context.Context, teamID uuid.UUID) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositoriesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Provider,
			&i.ProviderID,
			&i.Name,
			&i.FullName,
			&i.Url,
			&i.DefaultBranch,
			&i.AccessToken,
			&i.WebhookSecret,
			&i.Config,
			&i.IsActive,
			&i.LastScannedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepositoryConfig = `-- name: UpdateRepositoryConfig :one
UPDATE repositories
SET config = $1, updated_at = now()
WHERE id = $2
RETURNING id, team_id, provider, provider_id, name, full_name, url, default_branch, access_token, webhook_secret, config, is_active, last_scanned_at, created_at, updated_at
`

type UpdateRepositoryConfigParams struct {
	Config []byte    `json:"config"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateRepositoryConfig(ctx context.Context, arg UpdateRepositoryConfigParams) (Repository, error) {
	row := q.db.QueryRow(ctx, updateRepositoryConfig, arg.Config, arg.ID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Provider,
		&i.ProviderID,
		&i.Name,
		&i.FullName,
		&i.Url,
		&i.DefaultBranch,
		&i.AccessToken,
		&i.WebhookSecret,
		&i.Config,
		&i.IsActive,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRepositoryLastScanned = `-- name: UpdateRepositoryLastScanned :exec
UPDATE repositories
SET last_scanned_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateRepositoryLastScanned(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateRepositoryLastScanned, id)
	return err
}
