// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countPendingApprovalsByTeam = `-- name: CountPendingApprovalsByTeam :one
SELECT COUNT(*) FROM scans
WHERE team_id = $1 AND status = 'awaiting_approval'
`

func (q *Queries) CountPendingApprovalsByTeam(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingApprovalsByTeam, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScan = `-- name: CreateScan :one
INSERT INTO scans (
  team_id, repository_id, status, triggered_by,
  triggered_by_user_id, scan_from, scan_to, config_snapshot
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, team_id, repository_id, status, triggered_by, triggered_by_user_id, scan_from, scan_to, commit_count, filtered_count, error, config_snapshot, created_at, updated_at
`

type CreateScanParams struct {
	TeamID            uuid.UUID       `json:"team_id"`
	RepositoryID      uuid.UUID       `json:"repository_id"`
	Status            ScanStatus      `json:"status"`
	TriggeredBy       ScanTrigger     `json:"triggered_by"`
	TriggeredByUserID uuid.NullUUID   `json:"triggered_by_user_id"`
	ScanFrom          time.Time       `json:"scan_from"`
	ScanTo            time.Time       `json:"scan_to"`
	ConfigSnapshot    json.RawMessage `json:"config_snapshot"`
}

func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error) {
	row := q.db.QueryRowContext(ctx, createScan,
		arg.TeamID,
		arg.RepositoryID,
		arg.Status,
		arg.TriggeredBy,
		arg.TriggeredByUserID,
		arg.ScanFrom,
		arg.ScanTo,
		arg.ConfigSnapshot,
	)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RepositoryID,
		&i.Status,
		&i.TriggeredBy,
		&i.TriggeredByUserID,
		&i.ScanFrom,
		&i.ScanTo,
		&i.CommitCount,
		&i.FilteredCount,
		&i.Error,
		&i.ConfigSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScanByID = `-- name: GetScanByID :one
SELECT id, team_id, repository_id, status, triggered_by, triggered_by_user_id, scan_from, scan_to, commit_count, filtered_count, error, config_snapshot, created_at, updated_at FROM scans WHERE id = $1
`

func (q *Queries) GetScanByID(ctx context.Context, id uuid.UUID) (Scan, error) {
	row := q.db.QueryRowContext(ctx, getScanByID, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RepositoryID,
		&i.Status,
		&i.TriggeredBy,
		&i.TriggeredByUserID,
		&i.ScanFrom,
		&i.ScanTo,
		&i.CommitCount,
		&i.FilteredCount,
		&i.Error,
		&i.ConfigSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScansByRepository = `-- name: ListScansByRepository :many
SELECT id, team_id, repository_id, status, triggered_by, triggered_by_user_id, scan_from, scan_to, commit_count, filtered_count, error, config_snapshot, created_at, updated_at FROM scans
WHERE repository_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListScansByRepositoryParams struct {
	RepositoryID uuid.UUID `json:"repository_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) ListScansByRepository(ctx context.Context, arg ListScansByRepositoryParams) ([]Scan, error) {
	rows, err := q.db.QueryContext(ctx, listScansByRepository, arg.RepositoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.RepositoryID,
			&i.Status,
			&i.TriggeredBy,
			&i.TriggeredByUserID,
			&i.ScanFrom,
			&i.ScanTo,
			&i.CommitCount,
			&i.FilteredCount,
			&i.Error,
			&i.ConfigSnapshot,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScansByTeam = `-- name: ListScansByTeam :many
SELECT id, team_id, repository_id, status, triggered_by, triggered_by_user_id, scan_from, scan_to, commit_count, filtered_count, error, config_snapshot, created_at, updated_at FROM scans
WHERE team_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListScansByTeamParams struct {
	TeamID uuid.UUID `json:"team_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListScansByTeam(ctx context.Context, arg ListScansByTeamParams) ([]Scan, error) {
	rows, err := q.db.QueryContext(ctx, listScansByTeam, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.RepositoryID,
			&i.Status,
			&i.TriggeredBy,
			&i.TriggeredByUserID,
			&i.ScanFrom,
			&i.ScanTo,
			&i.CommitCount,
			&i.FilteredCount,
			&i.Error,
			&i.ConfigSnapshot,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScanCounts = `-- name: UpdateScanCounts :exec
UPDATE scans
SET commit_count = $1, filtered_count = $2, updated_at = now()
WHERE id = $3
`

type UpdateScanCountsParams struct {
	CommitCount   int32     `json:"commit_count"`
	FilteredCount int32     `json:"filtered_count"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateScanCounts(ctx context.Context, arg UpdateScanCountsParams) error {
	_, err := q.db.ExecContext(ctx, updateScanCounts, arg.CommitCount, arg.FilteredCount, arg.ID)
	return err
}

const updateScanStatus = `-- name: UpdateScanStatus :exec
UPDATE scans
SET status = $1, updated_at = now()
WHERE id = $2
`

type UpdateScanStatusParams struct {
	Status ScanStatus `json:"status"`
	ID     uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateScanStatus(ctx context.Context, arg UpdateScanStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateScanStatus, arg.Status, arg.ID)
	return err
}

const updateScanStatusWithError = `-- name: UpdateScanStatusWithError :exec
UPDATE scans
SET status = $1, error = $2, updated_at = now()
WHERE id = $3
`

type UpdateScanStatusWithErrorParams struct {
	Status ScanStatus     `json:"status"`
	Error  sql.NullString `json:"error"`
	ID     uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateScanStatusWithError(ctx context.Context, arg UpdateScanStatusWithErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateScanStatusWithError, arg.Status, arg.Error, arg.ID)
	return err
}
