// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at, updated_at, setup_complete, config
`

type CreateTeamParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.Slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SetupComplete,
		&i.Config,
	)
	return i, err
}

const createTeamWithSetup = `-- name: CreateTeamWithSetup :one
INSERT INTO teams (name, slug, setup_complete)
VALUES ($1, $2, $3)
RETURNING id, name, slug, created_at, updated_at, setup_complete, config
`

type CreateTeamWithSetupParams struct {
	Name          string `json:"name"`
	Slug          string `json:"slug"`
	SetupComplete bool   `json:"setup_complete"`
}

func (q *Queries) CreateTeamWithSetup(ctx context.Context, arg CreateTeamWithSetupParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeamWithSetup, arg.Name, arg.Slug, arg.SetupComplete)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SetupComplete,
		&i.Config,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, slug, created_at, updated_at, setup_complete, config FROM teams
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SetupComplete,
		&i.Config,
	)
	return i, err
}

const getTeamBySlug = `-- name: GetTeamBySlug :one
SELECT id, name, slug, created_at, updated_at, setup_complete, config FROM teams
WHERE slug = $1
`

func (q *Queries) GetTeamBySlug(ctx context.Context, slug string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamBySlug, slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SetupComplete,
		&i.Config,
	)
	return i, err
}

const getTeamConfig = `-- name: GetTeamConfig :one
SELECT config FROM teams
WHERE id = $1
`

func (q *Queries) GetTeamConfig(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getTeamConfig, id)
	var config []byte
	err := row.Scan(&config)
	return config, err
}

const isSetupComplete = `-- name: IsSetupComplete :one
SELECT setup_complete FROM teams LIMIT 1
`

func (q *Queries) IsSetupComplete(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, isSetupComplete)
	var setup_complete bool
	err := row.Scan(&setup_complete)
	return setup_complete, err
}

const markSetupComplete = `-- name: MarkSetupComplete :exec
UPDATE teams
SET setup_complete = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkSetupComplete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSetupComplete, id)
	return err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name = $1, updated_at = now()
WHERE id = $2
RETURNING id, name, slug, created_at, updated_at, setup_complete, config
`

type UpdateTeamParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam, arg.Name, arg.ID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SetupComplete,
		&i.Config,
	)
	return i, err
}

const updateTeamConfig = `-- name: UpdateTeamConfig :exec
UPDATE teams
SET config = $1, updated_at = now()
WHERE id = $2
`

type UpdateTeamConfigParams struct {
	Config []byte    `json:"config"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateTeamConfig(ctx context.Context, arg UpdateTeamConfigParams) error {
	_, err := q.db.Exec(ctx, updateTeamConfig, arg.Config, arg.ID)
	return err
}
