// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (team_id, email, name, avatar_url, role, provider, provider_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, team_id, email, name, avatar_url, role, provider, provider_id, created_at, updated_at
`

type CreateUserParams struct {
	TeamID     uuid.UUID      `json:"team_id"`
	Email      string         `json:"email"`
	Name       string         `json:"name"`
	AvatarUrl  sql.NullString `json:"avatar_url"`
	Role       UserRole       `json:"role"`
	Provider   string         `json:"provider"`
	ProviderID string         `json:"provider_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.TeamID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.Role,
		arg.Provider,
		arg.ProviderID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, team_id, email, name, avatar_url, role, provider, provider_id, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, team_id, email, name, avatar_url, role, provider, provider_id, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByProvider = `-- name: GetUserByProvider :one
SELECT id, team_id, email, name, avatar_url, role, provider, provider_id, created_at, updated_at FROM users
WHERE provider = $1 AND provider_id = $2
`

type GetUserByProviderParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByProvider, arg.Provider, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByTeam = `-- name: ListUsersByTeam :many
SELECT id, team_id, email, name, avatar_url, role, provider, provider_id, created_at, updated_at FROM users
WHERE team_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListUsersByTeam(ctx context.Context, teamID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.Role,
			&i.Provider,
			&i.ProviderID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $1, updated_at = now()
WHERE id = $2
RETURNING id, team_id, email, name, avatar_url, role, provider, provider_id, created_at, updated_at
`

type UpdateUserRoleParams struct {
	Role UserRole  `json:"role"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserRole, arg.Role, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (team_id, email, name, avatar_url, role, provider, provider_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (provider, provider_id) DO UPDATE
SET
  name       = EXCLUDED.name,
  avatar_url = EXCLUDED.avatar_url,
  updated_at = now()
RETURNING id, team_id, email, name, avatar_url, role, provider, provider_id, created_at, updated_at
`

type UpsertUserParams struct {
	TeamID     uuid.UUID      `json:"team_id"`
	Email      string         `json:"email"`
	Name       string         `json:"name"`
	AvatarUrl  sql.NullString `json:"avatar_url"`
	Role       UserRole       `json:"role"`
	Provider   string         `json:"provider"`
	ProviderID string         `json:"provider_id"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.TeamID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.Role,
		arg.Provider,
		arg.ProviderID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
