import nodemailer from 'nodemailer'
import {
  OutputPlugin,
  DeliverRequest,
  DeliverResponse,
  getFinalContent,
  runOutputPlugin,
} from '@narratorlog/sdk'

interface EmailConfig {
  to: string | string[]
  from?: string
  subject_prefix?: string
  smtp_host_env?: string
  smtp_port_env?: string
  smtp_user_env?: string
  smtp_pass_env?: string
}

class EmailOutputPlugin implements OutputPlugin {
  async deliver(request: DeliverRequest): Promise<DeliverResponse> {
    const config = request.config as unknown as EmailConfig

    if (!config.to) {
      return { success: false, error: 'to is required in config' }
    }

    const smtpHost = process.env[config.smtp_host_env ?? 'SMTP_HOST']
    const smtpPort = parseInt(process.env[config.smtp_port_env ?? 'SMTP_PORT'] ?? '587')
    const smtpUser = process.env[config.smtp_user_env ?? 'SMTP_USER']
    const smtpPass = process.env[config.smtp_pass_env ?? 'SMTP_PASS']

    if (!smtpHost || !smtpUser || !smtpPass) {
      return { success: false, error: 'SMTP_HOST, SMTP_USER and SMTP_PASS environment variables are required' }
    }

    const content = getFinalContent(request)
    const from = new Date(request.scan.scan_from).toLocaleDateString('en-GB', {
      day: 'numeric', month: 'long', year: 'numeric',
    })
    const to = new Date(request.scan.scan_to).toLocaleDateString('en-GB', {
      day: 'numeric', month: 'long', year: 'numeric',
    })

    const prefix = config.subject_prefix ? `${config.subject_prefix} ` : ''
    const subject = `${prefix}${request.scan.repository} — ${from} to ${to}`

    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpPort === 465,
      auth: { user: smtpUser, pass: smtpPass },
    })

    try {
      const info = await transporter.sendMail({
        from: config.from ?? smtpUser,
        to: Array.isArray(config.to) ? config.to.join(', ') : config.to,
        subject,
        text: content + '\n\nGenerated by narratorlog · narratorlog.dev',
        html: markdownToHtml(content),
      })

      return {
        success: true,
        reference: info.messageId,
        message: `Email sent to ${config.to}`,
      }
    } catch (err) {
      return { success: false, error: String(err) }
    }
  }
}

function markdownToHtml(markdown: string): string {
  return `<!DOCTYPE html>
<html>
<body style="font-family: -apple-system, sans-serif; max-width: 680px; margin: 0 auto; padding: 24px; color: #111;">
${markdown
  .split('\n')
  .map(line => {
    if (line.startsWith('## ')) return `<h2 style="margin-top:24px">${line.slice(3)}</h2>`
    if (line.startsWith('### ')) return `<h3 style="margin-top:16px">${line.slice(4)}</h3>`
    if (line.startsWith('- ') || line.startsWith('* ')) return `<li>${line.slice(2)}</li>`
    if (line.trim() === '') return '<br>'
    return `<p style="margin:4px 0">${line}</p>`
  })
  .join('\n')}
<hr style="margin-top:32px;border:none;border-top:1px solid #eee">
<p style="color:#999;font-size:12px">Generated by <a href="https://narratorlog.dev">narratorlog</a></p>
</body>
</html>`
}

runOutputPlugin(new EmailOutputPlugin())