import { Client } from '@notionhq/client'

type NotionBlock = NonNullable<
  Parameters<InstanceType<typeof Client>['pages']['create']>[0]['children']
>[number]
import {
  OutputPlugin,
  DeliverRequest,
  DeliverResponse,
  getFinalContent,
  runOutputPlugin,
} from '@narratorlog/sdk'

interface NotionConfig {
  page_id: string
  token_env?: string
}

class NotionOutputPlugin implements OutputPlugin {
  async deliver(request: DeliverRequest): Promise<DeliverResponse> {
    const config = request.config as unknown as NotionConfig

    const tokenEnv = config.token_env ?? 'NOTION_TOKEN'
    const token = process.env[tokenEnv]

    if (!token) {
      return { success: false, error: `${tokenEnv} environment variable not set` }
    }

    if (!config.page_id) {
      return { success: false, error: 'page_id is required in config' }
    }

    const content = getFinalContent(request)
    const notion = new Client({ auth: token })

    const from = new Date(request.scan.scan_from).toLocaleDateString('en-GB', {
      day: 'numeric', month: 'long', year: 'numeric',
    })
    const to = new Date(request.scan.scan_to).toLocaleDateString('en-GB', {
      day: 'numeric', month: 'long', year: 'numeric',
    })

    try {
      const page = await notion.pages.create({
        parent: { page_id: config.page_id },
        properties: {
          title: {
            title: [
              {
                text: {
                  content: `${request.scan.repository} — ${from} to ${to}`,
                },
              },
            ],
          },
        },
        children: [
          ...contentToBlocks(content),
          {
            object: 'block',
            type: 'paragraph',
            paragraph: {
              rich_text: [
                {
                  type: 'text',
                  text: { content: 'Generated by narratorlog · narratorlog.dev' },
                  annotations: { color: 'gray' },
                },
              ],
            },
          },
        ],
      })

      return {
        success: true,
        reference: `https://notion.so/${(page.id as string).replace(/-/g, '')}`,
        message: `Created Notion page`,
      }
    } catch (err) {
      return { success: false, error: String(err) }
    }
  }
}

function contentToBlocks(content: string): NotionBlock[] {
  const lines = content.split('\n')
  const blocks: NotionBlock[] = []

  for (const line of lines) {
    if (line.startsWith('## ')) {
      blocks.push({
        object: 'block',
        type: 'heading_2',
        heading_2: {
          rich_text: [{ type: 'text', text: { content: line.slice(3) } }],
        },
      })
    } else if (line.startsWith('### ')) {
      blocks.push({
        object: 'block',
        type: 'heading_3',
        heading_3: {
          rich_text: [{ type: 'text', text: { content: line.slice(4) } }],
        },
      })
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      blocks.push({
        object: 'block',
        type: 'bulleted_list_item',
        bulleted_list_item: {
          rich_text: [{ type: 'text', text: { content: line.slice(2) } }],
        },
      })
    } else if (line.trim() === '') {
      blocks.push({
        object: 'block',
        type: 'paragraph',
        paragraph: { rich_text: [] },
      })
    } else {
      // Chunk long paragraphs — Notion has a 2000 char limit per block
      const chunks = splitIntoChunks(line, 1900)
      for (const chunk of chunks) {
        blocks.push({
          object: 'block',
          type: 'paragraph',
          paragraph: {
            rich_text: [{ type: 'text', text: { content: chunk } }],
          },
        })
      }
    }
  }

  return blocks
}

function splitIntoChunks(text: string, maxLen: number): string[] {
  if (text.length <= maxLen) return [text]
  const chunks: string[] = []
  for (let i = 0; i < text.length; i += maxLen) {
    chunks.push(text.slice(i, i + maxLen))
  }
  return chunks
}

runOutputPlugin(new NotionOutputPlugin())